### ISSUE TITLE
Generate task domain labels.

### ISSUE THREAD

**Issue by dspluta** [modestbayes/graph_fmri#3]
1. For every subject behavioral file, identify (i) time points that separate win/loss domain changes, and (ii) midpoint of loss domain.
2. Use identified time points in (1) to slice preprocessed time series into Win 1, Loss 1, Loss 2, Win 2.

Each subject should have 140 trials total. There should be 35 trials in each of the segmented series Loss 1, Loss 2, and Win 2.  Because of removing the initial scanner warm-up data, Win 1 will only have around 20 trials.

**Comment by modestbayes** [comment]
See _create_labels_, _block_indices_, and _divide_time_series_ in _data_utils_.
